fix(deps): update dependency primereact to v10.9.6 (#1894)
This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
| [primereact](https://www.primereact.org)
([source](https://redirect.github.com/primefaces/primereact)) |
[`10.9.5` ->
`10.9.6`](https://renovatebot.com/diffs/npm/primereact/10.9.5/10.9.6) |
[![age](https://developer.mend.io/api/mc/badges/age/npm/primereact/10.9.6?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/primereact/10.9.6?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/primereact/10.9.5/10.9.6?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/primereact/10.9.5/10.9.6?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|

---

### Release Notes

<details>
<summary>primefaces/primereact (primereact)</summary>

###
[`v10.9.6`](https://redirect.github.com/primefaces/primereact/blob/HEAD/CHANGELOG.md#1096-2025-06-02)

[Compare
Source](https://redirect.github.com/primefaces/primereact/compare/10.9.5...10.9.6)

[Full
Changelog](https://redirect.github.com/primefaces/primereact/compare/10.9.5...10.9.6)

**Enhancements:**

- CascadeSelect: Missing panelClassName and panelStyle props
[#&#8203;8000](https://redirect.github.com/primefaces/primereact/issues/8000)
- CascadeSelect: Missing showClear prop
[#&#8203;8006](https://redirect.github.com/primefaces/primereact/issues/8006)
- MultiStateCheckbox: Missing id prop
[#&#8203;7997](https://redirect.github.com/primefaces/primereact/issues/7997)
- TreeSelect is missing onNodeClick and onNodeDoubleClick callbacks
[#&#8203;6778](https://redirect.github.com/primefaces/primereact/issues/6778)
- MultiStateCheckbox: Missing support for invalid and variant props
[#&#8203;8019](https://redirect.github.com/primefaces/primereact/issues/8019)
- Add showCloseIcon props to Dialog
[#&#8203;8053](https://redirect.github.com/primefaces/primereact/issues/8053)

**Fixed Bugs:**

- Datatable: CellEdit and general issues with portal editors
[#&#8203;7405](https://redirect.github.com/primefaces/primereact/issues/7405)
- InputNumber: numpad decimal separator for locales that use comma as
decimal separator
[#&#8203;7809](https://redirect.github.com/primefaces/primereact/issues/7809)
- Calendar: When text input is focused the date cannot be selected from
the first click on the panel
[#&#8203;7992](https://redirect.github.com/primefaces/primereact/issues/7992)
- MultiSelect: keyboard down event does not pass to MultiSelectPanel
component
[#&#8203;7756](https://redirect.github.com/primefaces/primereact/issues/7756)
- File Upload: selecting the same file twice removes the file
[#&#8203;7989](https://redirect.github.com/primefaces/primereact/issues/7989)
- DataTable: RowTogglerButton has no accessible name due to missing
expandLabel and collapseLabel in locale config
[#&#8203;8023](https://redirect.github.com/primefaces/primereact/issues/8023)
- MultiStateCheckbox: Conflicting aria-checked usage on both custom
container and native input
[#&#8203;8022](https://redirect.github.com/primefaces/primereact/issues/8022)
- FilterMatchMode: Missing enumeration case notIn
[#&#8203;8026](https://redirect.github.com/primefaces/primereact/issues/8026)
- MenuItem: template property causes p-focus on the first item in the
list
[#&#8203;7979](https://redirect.github.com/primefaces/primereact/issues/7979)
- DataTable: Incorrect grouping of rows when using the Paginator
[#&#8203;8011](https://redirect.github.com/primefaces/primereact/issues/8011)
- TriStateCheckbox: Missing id prop
[#&#8203;8018](https://redirect.github.com/primefaces/primereact/issues/8018)
- AutoComplete: Bad type when using custom template definitions
[#&#8203;7984](https://redirect.github.com/primefaces/primereact/issues/7984)
- Calendar: Manual Input breaking with dd M yy date format
[#&#8203;7675](https://redirect.github.com/primefaces/primereact/issues/7675)
- Galleria: doesn't work correctly if value is set dynamically
[#&#8203;7450](https://redirect.github.com/primefaces/primereact/issues/7450)
- Dropdown: onClick is called twice
[#&#8203;7941](https://redirect.github.com/primefaces/primereact/issues/7941)
- File Upload: Shows Nan undefined text when trying to clear the
uploaded file
[#&#8203;7949](https://redirect.github.com/primefaces/primereact/issues/7949)
- DataTable: CSV export includes empty trailing column
[#&#8203;7953](https://redirect.github.com/primefaces/primereact/issues/7953)
- PickList: Incorrect types in the documentation
[#&#8203;7938](https://redirect.github.com/primefaces/primereact/issues/7938)
- HELP ! DataTable : Column body component dropdown doesn't update
options when the source changes in the parent
[#&#8203;7987](https://redirect.github.com/primefaces/primereact/issues/7987)
- InputNumber: PR
[#&#8203;7868](https://redirect.github.com/primefaces/primereact/issues/7868)
(10.9.5) breaks existing code
[#&#8203;7977](https://redirect.github.com/primefaces/primereact/issues/7977)
- ListBox: Inconsistent casing in component interface:
ListboxPassThroughOptions should be ListBoxPassThroughOptions
[#&#8203;8020](https://redirect.github.com/primefaces/primereact/issues/8020)
- File Upload: Remove icon only works with double click when using
removeIcon prop
[#&#8203;8033](https://redirect.github.com/primefaces/primereact/issues/8033)
- DataTable: bugs when updating data
[#&#8203;7942](https://redirect.github.com/primefaces/primereact/issues/7942)
- Datatable: Expanding is erratic
[#&#8203;8031](https://redirect.github.com/primefaces/primereact/issues/8031)
- DataTable: Cancel edit row causes undefined error
[#&#8203;8043](https://redirect.github.com/primefaces/primereact/issues/8043)
- Calendar: invalid prevPropValue caused an error: Uncaught TypeError:
prevPropValue.getTime is not a function
[#&#8203;8042](https://redirect.github.com/primefaces/primereact/issues/8042)
- Column body function not re-executed when state value used inside
changes
[#&#8203;8055](https://redirect.github.com/primefaces/primereact/issues/8055)
- MultiSelect: A component is changing an uncontrolled input to be
controlled.
[#&#8203;7896](https://redirect.github.com/primefaces/primereact/issues/7896)
- MultiSelect has non-unique key warning
[#&#8203;8049](https://redirect.github.com/primefaces/primereact/issues/8049)

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined),
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update
again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR was generated by [Mend Renovate](https://mend.io/renovate/).
View the [repository job
log](https://developer.mend.io/github/ziyadedher/ziyadedher).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiI0MC4zMy42IiwidXBkYXRlZEluVmVyIjoiNDAuMzMuNiIsInRhcmdldEJyYW5jaCI6Im1haW4iLCJsYWJlbHMiOltdfQ==-->

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>