fix(deps): update dependency flowbite-react to v0.12.4 (#1968)
This PR contains the following updates:

| Package | Change | Age | Confidence |
|---|---|---|---|
| [flowbite-react](https://flowbite-react.com)
([source](https://redirect.github.com/themesberg/flowbite-react/tree/HEAD/packages/ui))
| [`0.12.3` ->
`0.12.4`](https://renovatebot.com/diffs/npm/flowbite-react/0.12.3/0.12.4)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/flowbite-react/0.12.4?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/flowbite-react/0.12.3/0.12.4?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|

---

### Release Notes

<details>
<summary>themesberg/flowbite-react (flowbite-react)</summary>

###
[`v0.12.4`](https://redirect.github.com/themesberg/flowbite-react/blob/HEAD/packages/ui/CHANGELOG.md#0124)

[Compare
Source](https://redirect.github.com/themesberg/flowbite-react/compare/flowbite-react@0.12.3...flowbite-react@0.12.4)

##### Patch Changes

-
[#&#8203;1607](https://redirect.github.com/themesberg/flowbite-react/pull/1607)
[`a89a098`](https://redirect.github.com/themesberg/flowbite-react/commit/a89a09808bc1a5227e614aa160d932890fb1b126)
Thanks
[@&#8203;SutuSebastian](https://redirect.github.com/SutuSebastian)! -
fix: `Error: Cannot find module 'tailwindcss/plugin'`

-
[#&#8203;1605](https://redirect.github.com/themesberg/flowbite-react/pull/1605)
[`262cde0`](https://redirect.github.com/themesberg/flowbite-react/commit/262cde0defd27ac0496cbb5a4f0dc08261f6e094)
Thanks
[@&#8203;SutuSebastian](https://redirect.github.com/SutuSebastian)! -
Search for `<ThemeInit />` in the project and warn if it's not found
instead of warning all the time

##### Changes

- during commands `build` and `dev` check files content for custom
configuration and display a warning if `<ThemeInit />` is not found
- switch tests in `src/cli` and `src/helpers` from `vitest` ->
`bun:test`

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined),
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update
again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR was generated by [Mend Renovate](https://mend.io/renovate/).
View the [repository job
log](https://developer.mend.io/github/ziyadedher/ziyadedher).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiI0MS40MC4wIiwidXBkYXRlZEluVmVyIjoiNDEuNDAuMCIsInRhcmdldEJyYW5jaCI6Im1haW4iLCJsYWJlbHMiOltdfQ==-->

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>