fix(deps): update dependency primereact to v10.5.3 (#1365)
[![Mend
Renovate](https://app.renovatebot.com/images/banner.svg)](https://renovatebot.com)

This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
| [primereact](https://www.primereact.org)
([source](https://togithub.com/primefaces/primereact)) | [`10.5.1` ->
`10.5.3`](https://renovatebot.com/diffs/npm/primereact/10.5.1/10.5.3) |
[![age](https://developer.mend.io/api/mc/badges/age/npm/primereact/10.5.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/primereact/10.5.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/primereact/10.5.1/10.5.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/primereact/10.5.1/10.5.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|

---

### Release Notes

<details>
<summary>primefaces/primereact (primereact)</summary>

###
[`v10.5.3`](https://togithub.com/primefaces/primereact/blob/HEAD/CHANGELOG.md#1053-2024-03-19)

[Compare
Source](https://togithub.com/primefaces/primereact/compare/10.5.2...10.5.3)

[Full
Changelog](https://togithub.com/primefaces/primereact/compare/10.5.2...10.5.3)

**Fixed bugs:**

- Messages Missing MergeProps
[#&#8203;6179](https://togithub.com/primefaces/primereact/issues/6179)

###
[`v10.5.2`](https://togithub.com/primefaces/primereact/blob/HEAD/CHANGELOG.md#1052-2024-03-19)

[Compare
Source](https://togithub.com/primefaces/primereact/compare/10.5.1...10.5.2)

[Full
Changelog](https://togithub.com/primefaces/primereact/compare/10.5.1...10.5.2)

**New Features:**

- Calendar: add 'hideOnRangeSelection' from PrimeVue
[#&#8203;5970](https://togithub.com/primefaces/primereact/issues/5970)
- New MeterGroup Component
[#&#8203;5977](https://togithub.com/primefaces/primereact/issues/5977)
- New invalid properties
[#&#8203;6139](https://togithub.com/primefaces/primereact/issues/6139)

**Enhancements:**

- Primereact uses document.getElementById(undefined) for appending
component styles
[#&#8203;6079](https://togithub.com/primefaces/primereact/issues/6079)
- InputNumber: onChange and onValueChange events are not triggered when
using keyboard shortcut for "cut" action
[#&#8203;6047](https://togithub.com/primefaces/primereact/issues/6047)
- StyleClass: deprecate enterClassName/leaveClassName use
enterFromClassName/leaveFromClassName
[#&#8203;6105](https://togithub.com/primefaces/primereact/issues/6105)
- Contrast and Secondary Variants for Badge/Tag/Message/Toast
[#&#8203;5985](https://togithub.com/primefaces/primereact/issues/5985)
- LastPageLink in Paginator: doesn't give "totalPages" in options
[#&#8203;5978](https://togithub.com/primefaces/primereact/issues/5978)
- Toast: onRemove's message changes its data structure
[#&#8203;5972](https://togithub.com/primefaces/primereact/issues/5972)
- Password: (accessiblility) cannot access toggle button using keyboard
[#&#8203;6046](https://togithub.com/primefaces/primereact/issues/6046)
- DataTable_BodyCell: Duplicate key "aria-label" in object literal
[#&#8203;6168](https://togithub.com/primefaces/primereact/issues/6168)
- Splitter: Accessibility updates
[#&#8203;6039](https://togithub.com/primefaces/primereact/issues/6039)
- Tree : Accessibility issues
[#&#8203;5426](https://togithub.com/primefaces/primereact/issues/5426)
- Primereact Dropdown accessibility. Value isn't being read by VoiceOver
screen reader.
[#&#8203;5836](https://togithub.com/primefaces/primereact/issues/5836)
- Multiselect: Accessibility issue aria-allowed-role - list-box role not
allowed
[#&#8203;5446](https://togithub.com/primefaces/primereact/issues/5446)
- ListBox: options not focusable using keyboard
[#&#8203;3672](https://togithub.com/primefaces/primereact/issues/3672)
- Dropdown: NVDA failed to read correctly readonly
[#&#8203;1413](https://togithub.com/primefaces/primereact/issues/1413)

**Fixed bugs:**

- MultiStateCheckbox: unstyled prop doesnt work properly
[#&#8203;6061](https://togithub.com/primefaces/primereact/issues/6061)
- Dropdown: unselects option when loses focus
[#&#8203;6035](https://togithub.com/primefaces/primereact/issues/6035)
- Image: Preview toolbar buttons only close the preview in unstyled
NextJS 14
[#&#8203;6037](https://togithub.com/primefaces/primereact/issues/6037)
- Dropdown component fails to expand the dropdown box after adding the
filter and editable properties.
[#&#8203;6027](https://togithub.com/primefaces/primereact/issues/6027)
- Tree: Lazy loaded tree crashes when using keyboard navigation (right
arrow) to expand
[#&#8203;6049](https://togithub.com/primefaces/primereact/issues/6049)
- DomHandler.js: getComputedStyle getPropertyValue should be in hyphen
case.
[#&#8203;6055](https://togithub.com/primefaces/primereact/issues/6055)
- AutoComplete: Resetting value doesn't work
[#&#8203;6044](https://togithub.com/primefaces/primereact/issues/6044)
- Chips: the component doesn't function properly on mobile devices
[#&#8203;6086](https://togithub.com/primefaces/primereact/issues/6086)
- MultiSelect: selectedOption undefined on MultiSelectChangeEvent
[#&#8203;6097](https://togithub.com/primefaces/primereact/issues/6097)
- Documentation: Problem with Dark Theme in Default column on Components
API section
[#&#8203;6125](https://togithub.com/primefaces/primereact/issues/6125)
- Datatable: Horizontal scroller with selection/checkbox resets to
initial position on clicking row
[#&#8203;3155](https://togithub.com/primefaces/primereact/issues/3155)
- Password: the feedback bar does not reset when I clear the field
[#&#8203;6119](https://togithub.com/primefaces/primereact/issues/6119)
- Slider: Null event.value within the onSlideEnd
[#&#8203;6101](https://togithub.com/primefaces/primereact/issues/6101)
- Typescript: update LocaleOptions interface
[#&#8203;6050](https://togithub.com/primefaces/primereact/issues/6050)
- Accordion/PanelMenu: (Tailwind) animation issues
[#&#8203;5540](https://togithub.com/primefaces/primereact/issues/5540)
- InputNumber onValueChange ignores Numpad Enter
[#&#8203;6107](https://togithub.com/primefaces/primereact/issues/6107)
- Dialog: inconsistency between theming documentation and used
classnames (from source code)
[#&#8203;6024](https://togithub.com/primefaces/primereact/issues/6024)
- OrganizationChart: Documentation issue in Basic and Template sections.
[#&#8203;6070](https://togithub.com/primefaces/primereact/issues/6070)
- TreeTable: Documentation issues
[#&#8203;6078](https://togithub.com/primefaces/primereact/issues/6078)
- Sidebar: "Pass Through" documentation corrections
[#&#8203;6068](https://togithub.com/primefaces/primereact/issues/6068)
- Speed Dial: TypeError: Cannot read properties of undefined (reading
'visible')
[#&#8203;6156](https://togithub.com/primefaces/primereact/issues/6156)
- TextInput: className property is written two times into the class
attribute in DOM
[#&#8203;6160](https://togithub.com/primefaces/primereact/issues/6160)
- Typo error in the DataTable documentation
[#&#8203;6147](https://togithub.com/primefaces/primereact/issues/6147)
- MultiSelect: loading prop in typescript shows error when called
[#&#8203;6113](https://togithub.com/primefaces/primereact/issues/6113)
- Documentation: Duplicate useState in HeadlessSidebar Demo Full Code
Example
[#&#8203;6033](https://togithub.com/primefaces/primereact/issues/6033)
- Tailwind: content does not exist in MenuPassThroughOption
[#&#8203;6063](https://togithub.com/primefaces/primereact/issues/6063)
- Tooltip component shows unstyled error
[#&#8203;6080](https://togithub.com/primefaces/primereact/issues/6080)
- Calendar: TypeScript Definitions do not match with actual PT props
[#&#8203;6094](https://togithub.com/primefaces/primereact/issues/6094)
- Tree_Drag and Drop: validateDropPoint function is throwing error
[#&#8203;6048](https://togithub.com/primefaces/primereact/issues/6048)
- Tree: Custom icon assignation is not working
[#&#8203;6116](https://togithub.com/primefaces/primereact/issues/6116)
- ConfirmDialog. Error message: "Warning: Invalid value for prop content
on div tag.
[#&#8203;6111](https://togithub.com/primefaces/primereact/issues/6111)
- Accordion: Wrong prop in TailwindDoc
[#&#8203;6132](https://togithub.com/primefaces/primereact/issues/6132)
- AutoComplete: event type in onInput prop is FormEvent-HtmlSpanElement
[#&#8203;6145](https://togithub.com/primefaces/primereact/issues/6145)
- Dropdown: editable prop requires optionLabel to be exactly "name" and
options object to contain a "name" key
[#&#8203;6076](https://togithub.com/primefaces/primereact/issues/6076)
- TreeTable: Accessibility navigation is triggered when editing a cell
following 10.3.3 update
[#&#8203;6018](https://togithub.com/primefaces/primereact/issues/6018)
- DataTable: Memory leak when data updated continuously
[#&#8203;5927](https://togithub.com/primefaces/primereact/issues/5927)
- DataTable: Virtual Scroller position resets upon lazy loaded
[#&#8203;6015](https://togithub.com/primefaces/primereact/issues/6015)
- Knobs: Wrong component shown in basic code example for React Hook Form
[#&#8203;6013](https://togithub.com/primefaces/primereact/issues/6013)
- Showcase: Problem For DataTable in TS
[#&#8203;6002](https://togithub.com/primefaces/primereact/issues/6002)
- useDisplayOrder: clears incorrect
[#&#8203;6000](https://togithub.com/primefaces/primereact/issues/6000)
- DataTable: Virtual Scroll error in dev mode
[#&#8203;6006](https://togithub.com/primefaces/primereact/issues/6006)
- Datatable + Virtual Scroller: Multiselect passes undefined to
onSelectionChange
[#&#8203;5870](https://togithub.com/primefaces/primereact/issues/5870)
- Dropdown: editable input get console error when optionValue is not
'name'
[#&#8203;6004](https://togithub.com/primefaces/primereact/issues/6004)
- DataTable: rowClassName don't take prevalence over passthrough
tailwind
[#&#8203;5983](https://togithub.com/primefaces/primereact/issues/5983)
- TabMenu is not updating its style when using unstyled mode and
controlled mode
[#&#8203;5992](https://togithub.com/primefaces/primereact/issues/5992)
- SelectButton: Inappropriate UI
[#&#8203;5841](https://togithub.com/primefaces/primereact/issues/5841)
- Calendar: using yearNavigator cause exception error
[#&#8203;5973](https://togithub.com/primefaces/primereact/issues/5973)
- MenubarSub: Each child in a list should have a unique "key" prop.
[#&#8203;5976](https://togithub.com/primefaces/primereact/issues/5976)
- Sidebar: Unable to write unit test:
groupToDisplayedElements'group'.findLastIndex is not a function
[#&#8203;5954](https://togithub.com/primefaces/primereact/issues/5954)
- BlockUI: setting blocked to false has no effect
[#&#8203;5889](https://togithub.com/primefaces/primereact/issues/5889)
- Select button accepts children but doesnt render them
[#&#8203;5888](https://togithub.com/primefaces/primereact/issues/5888)
- DataTableColReorderEvent.columns has a wrong type
[#&#8203;5962](https://togithub.com/primefaces/primereact/issues/5962)

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined),
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update
again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR has been generated by [Mend
Renovate](https://www.mend.io/free-developer-tools/renovate/). View
repository job log
[here](https://developer.mend.io/github/ziyadedher/ziyadedher).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzNy4yNDUuMCIsInVwZGF0ZWRJblZlciI6IjM3LjI0NS4wIiwidGFyZ2V0QnJhbmNoIjoibWFpbiJ9-->

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>